import { Tile } from "./dto/tile.dto";

export const Tiles : Tile[] = [
  {
    id : '1',
    name: 'default',
    source : 'assets/tiles/Tile_01.png',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '2',
    name: 'default',
    source : 'assets/tiles/Tile_02.png',
    image : undefined,
    paths : [[4,2], [2,4]],
    rotation: 0,
  },
  {
    id : '3',
    name: 'default',
    source : 'assets/tiles/Tile_03.png',
    image : undefined,
    paths : [[4,2], [2,4]],
    rotation: 0,
  },
  {
    id : '4',
    name: 'default',
    source : 'assets/tiles/Tile_04.png',
    image : undefined,
    paths : [[4,2], [2,4]],
    rotation: 0,
  },
  {
    id : '5',
    name: 'default',
    source : 'assets/tiles/Tile_05.png',
    image : undefined,
    paths : [[3,2], [2,3]],
    rotation: 0,
  },
  {
    id : '6',
    name: 'default',
    source : 'assets/tiles/Tile_06.png',
    image : undefined,
    paths : [[3,2], [2,3]],
    rotation: 0,
  },
  {
    id : '7',
    name: 'default',
    source : 'assets/tiles/Tile_07.png',
    image : undefined,
    paths : [[4,2], [2,4]],
    rotation: 0,
  },
  {
    id : '8',
    name: 'default',
    source : 'assets/tiles/Tile_08.png',
    image : undefined,
    paths : [[1,2], [2,1], [4,3], [3,4]],
    rotation: 0,
  },
  {
    id : '9',
    name: 'default',
    source : 'assets/tiles/Tile_09.png',
    image : undefined,
    paths : [[3,2], [2,3]],
    rotation: 0,
  },
  {
    id : '10',
    name: 'default',
    source : 'assets/tiles/Tile_10.png',
    image : undefined,
    paths : [[3,2], [2,3]],
    rotation: 0,
  },
  {
    id : '18.1',
    name: 'cross',
    source : 'assets/tiles/Tile_18-1.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '18.2',
    name: 'cross',
    source : 'assets/tiles/Tile_18-2.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '18.3',
    name: 'cross',
    source : 'assets/tiles/Tile_18-3.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '18.4',
    name: 'cross',
    source : 'assets/tiles/Tile_18-4.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '18.5',
    name: 'cross',
    source : 'assets/tiles/Tile_18-5.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  },
  {
    id : '18.6',
    name: 'cross',
    source : 'assets/tiles/Tile_18-6.svg',
    image : undefined,
    paths : [[0,3]],
    rotation: 0,
  }
]
