# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build and Publish
        run: |
          cd frontend
          docker login -u alexstecki -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t alexstecki/robocup-rescuemapeditor-frontend .
          docker push alexstecki/robocup-rescuemapeditor-frontend
          echo "Finish building frontend"
          
          cd ../backend
          docker build -t alexstecki/robocup-rescuemapeditor-backend .
          docker push alexstecki/robocup-rescuemapeditor-backend
          echo "Finish building backend"

      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
